[package]
name = "new_ship"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.10", features = ["bevy_audio"] }
bevy_audio = "0.10"
bevy_winit = "0.10"
rand = "0.8"  # Add this line to include the rand crate for random number generation
